const cardArray = [
  {
    id: 1,
    name: "Siddhartha Mukherjee",
    profile_image: "/images/img.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nu...",
    location: "Kolkata, West Bengal",
    practicing_since: "1 year",
    languages: [
      "English, Odia, Marathi, Kannada, Assamese, Telugu, Hindi, Bengali",
    ],
    rating: 4.7,
    reviews: 51,
    specialization: "Cyber Crime",
    rate_per_min: 39,
    availability: "Available",
  },
  {
    id: 2,
    name: "Rohan Basu",
    profile_image: "/images/img1.jpg",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industr...",
    location: "Kolkata, West Bengal",
    practicing_since: "3 years",
    languages: ["English"],
    rating: 4.3,
    reviews: 8,
    specialization: "Divorce & Child Custody",
    rate_per_min: 65,
    availability: "Available",
  },
  {
    id: 3,
    name: "Ankita Roy",
    profile_image: "/images/img1.jpg",
    description: "Expert in family law and child rights cases.",
    location: "Mumbai, Maharashtra",
    practicing_since: "5 years",
    languages: ["English, Hindi, Marathi"],
    rating: 4.9,
    reviews: 120,
    specialization: "Family Law",
    rate_per_min: 50,
    availability: "Busy",
  },
  {
    id: 4,
    name: "Rahul Sharma",
    profile_image: "/images/img.jpg",
    description: "Specialized in criminal defense and cyber law.",
    location: "Delhi, India",
    practicing_since: "7 years",
    languages: ["English, Hindi"],
    rating: 4.6,
    reviews: 95,
    specialization: "Criminal Defense",
    rate_per_min: 75,
    availability: "Available",
  },
  {
    id: 5,
    name: "Sneha Das",
    profile_image: "/images/img.jpg",
    description: "Proven expertise in property and real estate disputes.",
    location: "Bangalore, Karnataka",
    practicing_since: "4 years",
    languages: ["English, Kannada"],
    rating: 4.8,
    reviews: 68,
    specialization: "Property Law",
    rate_per_min: 60,
    availability: "Available",
  },
  {
    id: 6,
    name: "Arjun Menon",
    profile_image: "/images/img1.jpg",
    description: "Focused on corporate legal solutions and arbitration.",
    location: "Chennai, Tamil Nadu",
    practicing_since: "10 years",
    languages: ["English, Tamil"],
    rating: 4.7,
    reviews: 112,
    specialization: "Corporate Law",
    rate_per_min: 85,
    availability: "Available",
  },
];

export default cardArray;
